#!/usr/bin/env bash

# Based on the Taskfile format from https://github.com/adriancooney/Taskfile
# Please keep functions sorted alphabetically for ease of editing.

# A useful path mod
PATH=./node_modules/.bin:$PATH

#######################################################################
# Set some commonly used globals
#######################################################################
BASE_DIR=$(cd `dirname $0`; pwd)
PROJECT_NAME=`basename "$BASE_DIR"`

#######################################################################
# Function declarations
#######################################################################
function help { ## Display usage for this application
    echo "$0 <task> <args>"
    echo "Tasks:"
    # compgen -A function | cat -n
    grep -E '^function [a-zA-Z_-]+ {.*?## .*$' $0 | \
        sed -e 's/function //' | \
        sort | \
        awk 'BEGIN {FS = "{.*?## "}; {printf "\033[93m%-30s\033[92m %s\033[0m\n", $1, $2}'
}

function manage { ## Run Django manage.py commands (connects to running container or starts new one)
    # Check if Django container is running
    if docker ps --format '{{.Names}}' | grep -q '^webquills-django$'; then
        # Container is running, exec into it
        docker exec -it webquills-django python manage.py "$@"
    else
        # Container is not running, start a new one
        docker compose run --rm django python manage.py "$@"
    fi
}

#######################################################################
# Finally, execute it.
#######################################################################

TIMEFORMAT="Task completed in %3lR"
# Replace "help" with the name of the desired default function
time ${@:-help}
