# coding: utf-8

# flake8: noqa

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: {{AppVer | JSEscape}}
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ActivitypubApi",
    "AdminApi",
    "IssueApi",
    "MiscellaneousApi",
    "NotificationApi",
    "OrganizationApi",
    "PackageApi",
    "RepositoryApi",
    "SettingsApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIError",
    "AccessToken",
    "ActionTask",
    "ActionTaskResponse",
    "ActionVariable",
    "Activity",
    "ActivityPub",
    "AddCollaboratorOption",
    "AddTimeOption",
    "AnnotatedTag",
    "AnnotatedTagObject",
    "Attachment",
    "Badge",
    "Branch",
    "BranchProtection",
    "ChangeFileOperation",
    "ChangeFilesOptions",
    "ChangedFile",
    "CombinedStatus",
    "Comment",
    "Commit",
    "CommitAffectedFiles",
    "CommitDateOptions",
    "CommitMeta",
    "CommitStats",
    "CommitStatus",
    "CommitUser",
    "Compare",
    "ContentsResponse",
    "CreateAccessTokenOption",
    "CreateBranchProtectionOption",
    "CreateBranchRepoOption",
    "CreateEmailOption",
    "CreateFileOptions",
    "CreateForkOption",
    "CreateGPGKeyOption",
    "CreateHookOption",
    "CreateIssueCommentOption",
    "CreateIssueOption",
    "CreateKeyOption",
    "CreateLabelOption",
    "CreateMilestoneOption",
    "CreateOAuth2ApplicationOptions",
    "CreateOrUpdateSecretOption",
    "CreateOrgOption",
    "CreatePullRequestOption",
    "CreatePullReviewComment",
    "CreatePullReviewOptions",
    "CreatePushMirrorOption",
    "CreateReleaseOption",
    "CreateRepoOption",
    "CreateStatusOption",
    "CreateTagOption",
    "CreateTagProtectionOption",
    "CreateTeamOption",
    "CreateUserOption",
    "CreateVariableOption",
    "CreateWikiPageOptions",
    "Cron",
    "DeleteEmailOption",
    "DeleteFileOptions",
    "DeployKey",
    "DismissPullReviewOptions",
    "EditAttachmentOptions",
    "EditBranchProtectionOption",
    "EditDeadlineOption",
    "EditGitHookOption",
    "EditHookOption",
    "EditIssueCommentOption",
    "EditIssueOption",
    "EditLabelOption",
    "EditMilestoneOption",
    "EditOrgOption",
    "EditPullRequestOption",
    "EditReactionOption",
    "EditReleaseOption",
    "EditRepoOption",
    "EditTagProtectionOption",
    "EditTeamOption",
    "EditUserOption",
    "Email",
    "ExternalTracker",
    "ExternalWiki",
    "FileCommitResponse",
    "FileDeleteResponse",
    "FileLinksResponse",
    "FileResponse",
    "FilesResponse",
    "GPGKey",
    "GPGKeyEmail",
    "GeneralAPISettings",
    "GeneralAttachmentSettings",
    "GeneralRepoSettings",
    "GeneralUISettings",
    "GenerateRepoOption",
    "GitBlobResponse",
    "GitEntry",
    "GitHook",
    "GitObject",
    "GitTreeResponse",
    "GitignoreTemplateInfo",
    "Hook",
    "Identity",
    "InternalTracker",
    "Issue",
    "IssueConfig",
    "IssueConfigContactLink",
    "IssueConfigValidation",
    "IssueDeadline",
    "IssueFormField",
    "IssueLabelsOption",
    "IssueMeta",
    "IssueTemplate",
    "Label",
    "LabelTemplate",
    "LicenseTemplateInfo",
    "LicensesTemplateListEntry",
    "MarkdownOption",
    "MarkupOption",
    "MergePullRequestOption",
    "MergeUpstreamRequest",
    "MergeUpstreamResponse",
    "MigrateRepoOptions",
    "Milestone",
    "NewIssuePinsAllowed",
    "NodeInfo",
    "NodeInfoServices",
    "NodeInfoSoftware",
    "NodeInfoUsage",
    "NodeInfoUsageUsers",
    "Note",
    "NotificationCount",
    "NotificationSubject",
    "NotificationThread",
    "OAuth2Application",
    "Organization",
    "OrganizationPermissions",
    "PRBranchInfo",
    "Package",
    "PackageFile",
    "PayloadCommit",
    "PayloadCommitVerification",
    "PayloadUser",
    "Permission",
    "PublicKey",
    "PullRequest",
    "PullRequestMeta",
    "PullReview",
    "PullReviewComment",
    "PullReviewRequestOptions",
    "PushMirror",
    "Reaction",
    "Reference",
    "Release",
    "RenameUserOption",
    "RepoCollaboratorPermission",
    "RepoCommit",
    "RepoCreateReleaseAttachmentRequest",
    "RepoTopicOptions",
    "RepoTransfer",
    "Repository",
    "RepositoryMeta",
    "SearchResults",
    "Secret",
    "ServerVersion",
    "StopWatch",
    "SubmitPullReviewOptions",
    "Tag",
    "TagProtection",
    "Team",
    "TeamSearch200Response",
    "TimelineComment",
    "TopicName",
    "TopicResponse",
    "TrackedTime",
    "TransferRepoOption",
    "UpdateBranchProtectionPriories",
    "UpdateBranchRepoOption",
    "UpdateFileOptions",
    "UpdateRepoAvatarOption",
    "UpdateUserAvatarOption",
    "UpdateVariableOption",
    "User",
    "UserBadgeOption",
    "UserHeatmapData",
    "UserSearch200Response",
    "UserSettings",
    "UserSettingsOptions",
    "WatchInfo",
    "WikiCommit",
    "WikiCommitList",
    "WikiPage",
    "WikiPageMetaData",
]

# import apis into sdk package
from gitea_client.api.activitypub_api import ActivitypubApi as ActivitypubApi
from gitea_client.api.admin_api import AdminApi as AdminApi
from gitea_client.api.issue_api import IssueApi as IssueApi
from gitea_client.api.miscellaneous_api import MiscellaneousApi as MiscellaneousApi
from gitea_client.api.notification_api import NotificationApi as NotificationApi
from gitea_client.api.organization_api import OrganizationApi as OrganizationApi
from gitea_client.api.package_api import PackageApi as PackageApi
from gitea_client.api.repository_api import RepositoryApi as RepositoryApi
from gitea_client.api.settings_api import SettingsApi as SettingsApi
from gitea_client.api.user_api import UserApi as UserApi

# import ApiClient
from gitea_client.api_response import ApiResponse as ApiResponse
from gitea_client.api_client import ApiClient as ApiClient
from gitea_client.configuration import Configuration as Configuration
from gitea_client.exceptions import OpenApiException as OpenApiException
from gitea_client.exceptions import ApiTypeError as ApiTypeError
from gitea_client.exceptions import ApiValueError as ApiValueError
from gitea_client.exceptions import ApiKeyError as ApiKeyError
from gitea_client.exceptions import ApiAttributeError as ApiAttributeError
from gitea_client.exceptions import ApiException as ApiException

# import models into sdk package
from gitea_client.models.api_error import APIError as APIError
from gitea_client.models.access_token import AccessToken as AccessToken
from gitea_client.models.action_task import ActionTask as ActionTask
from gitea_client.models.action_task_response import ActionTaskResponse as ActionTaskResponse
from gitea_client.models.action_variable import ActionVariable as ActionVariable
from gitea_client.models.activity import Activity as Activity
from gitea_client.models.activity_pub import ActivityPub as ActivityPub
from gitea_client.models.add_collaborator_option import AddCollaboratorOption as AddCollaboratorOption
from gitea_client.models.add_time_option import AddTimeOption as AddTimeOption
from gitea_client.models.annotated_tag import AnnotatedTag as AnnotatedTag
from gitea_client.models.annotated_tag_object import AnnotatedTagObject as AnnotatedTagObject
from gitea_client.models.attachment import Attachment as Attachment
from gitea_client.models.badge import Badge as Badge
from gitea_client.models.branch import Branch as Branch
from gitea_client.models.branch_protection import BranchProtection as BranchProtection
from gitea_client.models.change_file_operation import ChangeFileOperation as ChangeFileOperation
from gitea_client.models.change_files_options import ChangeFilesOptions as ChangeFilesOptions
from gitea_client.models.changed_file import ChangedFile as ChangedFile
from gitea_client.models.combined_status import CombinedStatus as CombinedStatus
from gitea_client.models.comment import Comment as Comment
from gitea_client.models.commit import Commit as Commit
from gitea_client.models.commit_affected_files import CommitAffectedFiles as CommitAffectedFiles
from gitea_client.models.commit_date_options import CommitDateOptions as CommitDateOptions
from gitea_client.models.commit_meta import CommitMeta as CommitMeta
from gitea_client.models.commit_stats import CommitStats as CommitStats
from gitea_client.models.commit_status import CommitStatus as CommitStatus
from gitea_client.models.commit_user import CommitUser as CommitUser
from gitea_client.models.compare import Compare as Compare
from gitea_client.models.contents_response import ContentsResponse as ContentsResponse
from gitea_client.models.create_access_token_option import CreateAccessTokenOption as CreateAccessTokenOption
from gitea_client.models.create_branch_protection_option import CreateBranchProtectionOption as CreateBranchProtectionOption
from gitea_client.models.create_branch_repo_option import CreateBranchRepoOption as CreateBranchRepoOption
from gitea_client.models.create_email_option import CreateEmailOption as CreateEmailOption
from gitea_client.models.create_file_options import CreateFileOptions as CreateFileOptions
from gitea_client.models.create_fork_option import CreateForkOption as CreateForkOption
from gitea_client.models.create_gpg_key_option import CreateGPGKeyOption as CreateGPGKeyOption
from gitea_client.models.create_hook_option import CreateHookOption as CreateHookOption
from gitea_client.models.create_issue_comment_option import CreateIssueCommentOption as CreateIssueCommentOption
from gitea_client.models.create_issue_option import CreateIssueOption as CreateIssueOption
from gitea_client.models.create_key_option import CreateKeyOption as CreateKeyOption
from gitea_client.models.create_label_option import CreateLabelOption as CreateLabelOption
from gitea_client.models.create_milestone_option import CreateMilestoneOption as CreateMilestoneOption
from gitea_client.models.create_o_auth2_application_options import CreateOAuth2ApplicationOptions as CreateOAuth2ApplicationOptions
from gitea_client.models.create_or_update_secret_option import CreateOrUpdateSecretOption as CreateOrUpdateSecretOption
from gitea_client.models.create_org_option import CreateOrgOption as CreateOrgOption
from gitea_client.models.create_pull_request_option import CreatePullRequestOption as CreatePullRequestOption
from gitea_client.models.create_pull_review_comment import CreatePullReviewComment as CreatePullReviewComment
from gitea_client.models.create_pull_review_options import CreatePullReviewOptions as CreatePullReviewOptions
from gitea_client.models.create_push_mirror_option import CreatePushMirrorOption as CreatePushMirrorOption
from gitea_client.models.create_release_option import CreateReleaseOption as CreateReleaseOption
from gitea_client.models.create_repo_option import CreateRepoOption as CreateRepoOption
from gitea_client.models.create_status_option import CreateStatusOption as CreateStatusOption
from gitea_client.models.create_tag_option import CreateTagOption as CreateTagOption
from gitea_client.models.create_tag_protection_option import CreateTagProtectionOption as CreateTagProtectionOption
from gitea_client.models.create_team_option import CreateTeamOption as CreateTeamOption
from gitea_client.models.create_user_option import CreateUserOption as CreateUserOption
from gitea_client.models.create_variable_option import CreateVariableOption as CreateVariableOption
from gitea_client.models.create_wiki_page_options import CreateWikiPageOptions as CreateWikiPageOptions
from gitea_client.models.cron import Cron as Cron
from gitea_client.models.delete_email_option import DeleteEmailOption as DeleteEmailOption
from gitea_client.models.delete_file_options import DeleteFileOptions as DeleteFileOptions
from gitea_client.models.deploy_key import DeployKey as DeployKey
from gitea_client.models.dismiss_pull_review_options import DismissPullReviewOptions as DismissPullReviewOptions
from gitea_client.models.edit_attachment_options import EditAttachmentOptions as EditAttachmentOptions
from gitea_client.models.edit_branch_protection_option import EditBranchProtectionOption as EditBranchProtectionOption
from gitea_client.models.edit_deadline_option import EditDeadlineOption as EditDeadlineOption
from gitea_client.models.edit_git_hook_option import EditGitHookOption as EditGitHookOption
from gitea_client.models.edit_hook_option import EditHookOption as EditHookOption
from gitea_client.models.edit_issue_comment_option import EditIssueCommentOption as EditIssueCommentOption
from gitea_client.models.edit_issue_option import EditIssueOption as EditIssueOption
from gitea_client.models.edit_label_option import EditLabelOption as EditLabelOption
from gitea_client.models.edit_milestone_option import EditMilestoneOption as EditMilestoneOption
from gitea_client.models.edit_org_option import EditOrgOption as EditOrgOption
from gitea_client.models.edit_pull_request_option import EditPullRequestOption as EditPullRequestOption
from gitea_client.models.edit_reaction_option import EditReactionOption as EditReactionOption
from gitea_client.models.edit_release_option import EditReleaseOption as EditReleaseOption
from gitea_client.models.edit_repo_option import EditRepoOption as EditRepoOption
from gitea_client.models.edit_tag_protection_option import EditTagProtectionOption as EditTagProtectionOption
from gitea_client.models.edit_team_option import EditTeamOption as EditTeamOption
from gitea_client.models.edit_user_option import EditUserOption as EditUserOption
from gitea_client.models.email import Email as Email
from gitea_client.models.external_tracker import ExternalTracker as ExternalTracker
from gitea_client.models.external_wiki import ExternalWiki as ExternalWiki
from gitea_client.models.file_commit_response import FileCommitResponse as FileCommitResponse
from gitea_client.models.file_delete_response import FileDeleteResponse as FileDeleteResponse
from gitea_client.models.file_links_response import FileLinksResponse as FileLinksResponse
from gitea_client.models.file_response import FileResponse as FileResponse
from gitea_client.models.files_response import FilesResponse as FilesResponse
from gitea_client.models.gpg_key import GPGKey as GPGKey
from gitea_client.models.gpg_key_email import GPGKeyEmail as GPGKeyEmail
from gitea_client.models.general_api_settings import GeneralAPISettings as GeneralAPISettings
from gitea_client.models.general_attachment_settings import GeneralAttachmentSettings as GeneralAttachmentSettings
from gitea_client.models.general_repo_settings import GeneralRepoSettings as GeneralRepoSettings
from gitea_client.models.general_ui_settings import GeneralUISettings as GeneralUISettings
from gitea_client.models.generate_repo_option import GenerateRepoOption as GenerateRepoOption
from gitea_client.models.git_blob_response import GitBlobResponse as GitBlobResponse
from gitea_client.models.git_entry import GitEntry as GitEntry
from gitea_client.models.git_hook import GitHook as GitHook
from gitea_client.models.git_object import GitObject as GitObject
from gitea_client.models.git_tree_response import GitTreeResponse as GitTreeResponse
from gitea_client.models.gitignore_template_info import GitignoreTemplateInfo as GitignoreTemplateInfo
from gitea_client.models.hook import Hook as Hook
from gitea_client.models.identity import Identity as Identity
from gitea_client.models.internal_tracker import InternalTracker as InternalTracker
from gitea_client.models.issue import Issue as Issue
from gitea_client.models.issue_config import IssueConfig as IssueConfig
from gitea_client.models.issue_config_contact_link import IssueConfigContactLink as IssueConfigContactLink
from gitea_client.models.issue_config_validation import IssueConfigValidation as IssueConfigValidation
from gitea_client.models.issue_deadline import IssueDeadline as IssueDeadline
from gitea_client.models.issue_form_field import IssueFormField as IssueFormField
from gitea_client.models.issue_labels_option import IssueLabelsOption as IssueLabelsOption
from gitea_client.models.issue_meta import IssueMeta as IssueMeta
from gitea_client.models.issue_template import IssueTemplate as IssueTemplate
from gitea_client.models.label import Label as Label
from gitea_client.models.label_template import LabelTemplate as LabelTemplate
from gitea_client.models.license_template_info import LicenseTemplateInfo as LicenseTemplateInfo
from gitea_client.models.licenses_template_list_entry import LicensesTemplateListEntry as LicensesTemplateListEntry
from gitea_client.models.markdown_option import MarkdownOption as MarkdownOption
from gitea_client.models.markup_option import MarkupOption as MarkupOption
from gitea_client.models.merge_pull_request_option import MergePullRequestOption as MergePullRequestOption
from gitea_client.models.merge_upstream_request import MergeUpstreamRequest as MergeUpstreamRequest
from gitea_client.models.merge_upstream_response import MergeUpstreamResponse as MergeUpstreamResponse
from gitea_client.models.migrate_repo_options import MigrateRepoOptions as MigrateRepoOptions
from gitea_client.models.milestone import Milestone as Milestone
from gitea_client.models.new_issue_pins_allowed import NewIssuePinsAllowed as NewIssuePinsAllowed
from gitea_client.models.node_info import NodeInfo as NodeInfo
from gitea_client.models.node_info_services import NodeInfoServices as NodeInfoServices
from gitea_client.models.node_info_software import NodeInfoSoftware as NodeInfoSoftware
from gitea_client.models.node_info_usage import NodeInfoUsage as NodeInfoUsage
from gitea_client.models.node_info_usage_users import NodeInfoUsageUsers as NodeInfoUsageUsers
from gitea_client.models.note import Note as Note
from gitea_client.models.notification_count import NotificationCount as NotificationCount
from gitea_client.models.notification_subject import NotificationSubject as NotificationSubject
from gitea_client.models.notification_thread import NotificationThread as NotificationThread
from gitea_client.models.o_auth2_application import OAuth2Application as OAuth2Application
from gitea_client.models.organization import Organization as Organization
from gitea_client.models.organization_permissions import OrganizationPermissions as OrganizationPermissions
from gitea_client.models.pr_branch_info import PRBranchInfo as PRBranchInfo
from gitea_client.models.package import Package as Package
from gitea_client.models.package_file import PackageFile as PackageFile
from gitea_client.models.payload_commit import PayloadCommit as PayloadCommit
from gitea_client.models.payload_commit_verification import PayloadCommitVerification as PayloadCommitVerification
from gitea_client.models.payload_user import PayloadUser as PayloadUser
from gitea_client.models.permission import Permission as Permission
from gitea_client.models.public_key import PublicKey as PublicKey
from gitea_client.models.pull_request import PullRequest as PullRequest
from gitea_client.models.pull_request_meta import PullRequestMeta as PullRequestMeta
from gitea_client.models.pull_review import PullReview as PullReview
from gitea_client.models.pull_review_comment import PullReviewComment as PullReviewComment
from gitea_client.models.pull_review_request_options import PullReviewRequestOptions as PullReviewRequestOptions
from gitea_client.models.push_mirror import PushMirror as PushMirror
from gitea_client.models.reaction import Reaction as Reaction
from gitea_client.models.reference import Reference as Reference
from gitea_client.models.release import Release as Release
from gitea_client.models.rename_user_option import RenameUserOption as RenameUserOption
from gitea_client.models.repo_collaborator_permission import RepoCollaboratorPermission as RepoCollaboratorPermission
from gitea_client.models.repo_commit import RepoCommit as RepoCommit
from gitea_client.models.repo_create_release_attachment_request import RepoCreateReleaseAttachmentRequest as RepoCreateReleaseAttachmentRequest
from gitea_client.models.repo_topic_options import RepoTopicOptions as RepoTopicOptions
from gitea_client.models.repo_transfer import RepoTransfer as RepoTransfer
from gitea_client.models.repository import Repository as Repository
from gitea_client.models.repository_meta import RepositoryMeta as RepositoryMeta
from gitea_client.models.search_results import SearchResults as SearchResults
from gitea_client.models.secret import Secret as Secret
from gitea_client.models.server_version import ServerVersion as ServerVersion
from gitea_client.models.stop_watch import StopWatch as StopWatch
from gitea_client.models.submit_pull_review_options import SubmitPullReviewOptions as SubmitPullReviewOptions
from gitea_client.models.tag import Tag as Tag
from gitea_client.models.tag_protection import TagProtection as TagProtection
from gitea_client.models.team import Team as Team
from gitea_client.models.team_search200_response import TeamSearch200Response as TeamSearch200Response
from gitea_client.models.timeline_comment import TimelineComment as TimelineComment
from gitea_client.models.topic_name import TopicName as TopicName
from gitea_client.models.topic_response import TopicResponse as TopicResponse
from gitea_client.models.tracked_time import TrackedTime as TrackedTime
from gitea_client.models.transfer_repo_option import TransferRepoOption as TransferRepoOption
from gitea_client.models.update_branch_protection_priories import UpdateBranchProtectionPriories as UpdateBranchProtectionPriories
from gitea_client.models.update_branch_repo_option import UpdateBranchRepoOption as UpdateBranchRepoOption
from gitea_client.models.update_file_options import UpdateFileOptions as UpdateFileOptions
from gitea_client.models.update_repo_avatar_option import UpdateRepoAvatarOption as UpdateRepoAvatarOption
from gitea_client.models.update_user_avatar_option import UpdateUserAvatarOption as UpdateUserAvatarOption
from gitea_client.models.update_variable_option import UpdateVariableOption as UpdateVariableOption
from gitea_client.models.user import User as User
from gitea_client.models.user_badge_option import UserBadgeOption as UserBadgeOption
from gitea_client.models.user_heatmap_data import UserHeatmapData as UserHeatmapData
from gitea_client.models.user_search200_response import UserSearch200Response as UserSearch200Response
from gitea_client.models.user_settings import UserSettings as UserSettings
from gitea_client.models.user_settings_options import UserSettingsOptions as UserSettingsOptions
from gitea_client.models.watch_info import WatchInfo as WatchInfo
from gitea_client.models.wiki_commit import WikiCommit as WikiCommit
from gitea_client.models.wiki_commit_list import WikiCommitList as WikiCommitList
from gitea_client.models.wiki_page import WikiPage as WikiPage
from gitea_client.models.wiki_page_meta_data import WikiPageMetaData as WikiPageMetaData

