"""
Generated by 'django-admin startproject'.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/


See also https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

"""

import sys
from importlib.util import find_spec
from pathlib import Path

import environ

PROJECT = __name__.split(".")[0]

#######################################################################################
# SECTION 0: Application definition, settings that should not vary between environments
#######################################################################################
WSGI_APPLICATION = f"{PROJECT}.wsgi.application"
ROOT_URLCONF = f"{PROJECT}.urls"

INSTALLED_APPS = [
    # Add your custom apps here:
    "sitebuilder",
    # Third party apps:
    "crispy_forms",
    "crispy_bootstrap5",
    "django_bootstrap5",
    "django_extensions",
    "django_rq",
    # django-allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.mfa",
    # Core Django apps below custom so we can override their templates
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
]
SITE_ID = 1  # For the sites framework

MIDDLEWARE = [
    # https://docs.djangoproject.com/en/5.2/ref/middleware/#django.middleware.security.SecurityMiddleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # https://docs.djangoproject.com/en/5.2/ref/clickjacking/
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Set request.site by checking for a Site where domain is the host header
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
    # django-allauth middleware
    "allauth.account.middleware.AccountMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
            ],
        },
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-US"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#######################################################################################
# SECTION: Settings that can (and maybe should) differ between environments
#######################################################################################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Get environment settings
env = environ.Env(interpolate=True)
DOTENV = BASE_DIR / ".env"
if DOTENV.exists() and not env("IGNORE_ENV_FILE", default=False):
    environ.Env.read_env(DOTENV)

# Local data written by the app should be kept in one directory for ease of backup.
# In DEV this can be a subdir of BASE_DIR. In production, for single-server setups
# this should be a directory outside BASE_DIR that is backed up on a regular basis.
# For scalable configurations, you should not use local paths but external services
# like S3 and a dedicated database server.
DATA_DIR = Path(env("DATA_DIR", default=BASE_DIR.joinpath("var")))
DATA_DIR.mkdir(parents=True, exist_ok=True)

# SECRET_KEY intentionally has no default, and will error if not provided
# in the environment. This ensures you don't accidentally run with an
# insecure configuration in production.
SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG", default=False)
ALLOWED_HOSTS = env("ALLOWED_HOSTS", default=[])

#######################################################################################
# SECTION: Authentication and security settings
#######################################################################################
# django-allauth configuration
# https://docs.allauth.org/en/latest/
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of allauth
    "django.contrib.auth.backends.ModelBackend",
    # allauth specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Account settings
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_VERIFICATION = "optional" if DEBUG else "mandatory"
ACCOUNT_ADAPTER = "sitebuilder.adapters.AccountAdapter"
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_LOGIN_BY_CODE_TIMEOUT = 1800  # 30 minutes

# Redirect settings
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/profile/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

# MFA settings (webauthn to be added later)
MFA_SUPPORTED_TYPES = ["totp", "recovery_codes"]
MFA_PASSKEY_LOGIN_ENABLED = True

# Social account settings. Note: we're storing APPS (credentials) in the database,
# not here.
# https://docs.allauth.org/en/latest/socialaccount/providers/index.html
SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "EMAIL_AUTHENTICATION": True,  # Trust email from GitHub
        # Technically not using scopes because we're a GitHub App, not an OAuth App,
        # but for documentation purposes:
        "SCOPE": ["user", "repo", "read:org"],
        "VERIFIED_EMAIL": True,  # Consider GitHub emails verified
    },
}
# Don't trust 3rd party emails by default. We'll enable this per-provider as needed
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
# If we trust the provider's email, we can auto-connect social accounts
# to existing users with the same email address. This prevents users
# from having to manually connect their social accounts after logging in.
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# Automatically create user accounts on successful social login
SOCIALACCOUNT_AUTO_SIGNUP = True
# In order to access services on behalf of the user, we need to store the tokens
SOCIALACCOUNT_STORE_TOKENS = True
# End django-allauth configuration

# https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-ssl-redirect
SECURE_SSL_REDIRECT = False
if env.bool("USE_TLS", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = DATA_DIR / "www" / "static"
STATIC_ROOT.mkdir(parents=True, exist_ok=True)
MEDIA_URL = "/media/"
MEDIA_ROOT = DATA_DIR / "www" / "media"
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# Javascript / CSS assets being served from cache.
# See https://docs.djangoproject.com/en/5.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
# But for production, you almost certainly should be using a shared storage backend, like:
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
STORAGES = {
    "default": {
        "BACKEND": env(
            "DEFAULT_STORAGE", default="django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": env(
            "STATICFILES_STORAGE",
            default="django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        ),
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DB_DIR = DATA_DIR / "db"
DB_DIR.mkdir(parents=True, exist_ok=True)
SQLITE_DB = DB_DIR / "db.sqlite3"
DATABASES = {"default": env.db("DATABASE_URL", default=f"sqlite:///{SQLITE_DB}")}

# Optimal SQLite configuration
# https://docs.djangoproject.com/en/5.2/ref/databases/#sqlite-notes
# https://alldjango.com/articles/definitive-guide-to-using-django-sqlite-in-production
if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    # Merge optimal defaults with any existing options
    sqlite_defaults = {
        "transaction_mode": "IMMEDIATE",
        "timeout": 5,  # seconds
        "init_command": """
            PRAGMA journal_mode=WAL;
            PRAGMA synchronous=NORMAL;
            PRAGMA temp_store=MEMORY;
            PRAGMA mmap_size=268435456;
            PRAGMA journal_size_limit=27103364;
            PRAGMA cache_size=2000;
        """,
    }
    existing_options = DATABASES["default"].get("OPTIONS", {})
    DATABASES["default"]["OPTIONS"] = {**sqlite_defaults, **existing_options}

# If there is a REDIS_URL in the environment, use it for caching.
# Otherwise default to local memory caching.
if env("REDIS_URL", default=""):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env("REDIS_URL"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
else:
    # Default to local memory caching, which is not suitable for production.
    CACHES = {"default": env.cache("CACHE_URL", default="locmemcache://")}

# Email settings don't use a dict. Add to local vars instead.
# https://django-environ.readthedocs.io/en/latest/#email-settings
EMAIL_CONFIG = env.email_url("EMAIL_URL", default="consolemail://")
vars().update(EMAIL_CONFIG)

#######################################################################################
# SECTION: Configuration for third party apps
#######################################################################################
# django-crispy-forms settings
# https://django-crispy-forms.readthedocs.io/en/latest/install.html
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

BOOTSTRAP5 = {
    # The complete URL to the Bootstrap CSS file.
    # Note that a URL can be either a string
    # ("https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"),
    # or a dict with keys `url`, `integrity` and `crossorigin` like the default value below.
    "css_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css",
        "integrity": "sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB",
        "crossorigin": "anonymous",
    },
    # The complete URL to the Bootstrap bundle JavaScript file.
    "javascript_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js",
        "integrity": "sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI",
        "crossorigin": "anonymous",
    },
    # The complete URL to the Bootstrap CSS theme file (None means no theme).
    "theme_url": None,
}

#######################################################################################
# SECTION: Celery configuration
#######################################################################################
# If the environment has not provided settings, assume there is no broker
# and run celery tasks in-process. This means you MUST provide
# CELERY_TASK_ALWAYS_EAGER=False in your environment to actually use celery.
CELERY_TASK_ALWAYS_EAGER = env("CELERY_TASK_ALWAYS_EAGER", default=True)
CELERY_TASK_EAGER_PROPAGATES = env("CELERY_TASK_EAGER_PROPAGATES", default=True)
# For development setup, assume default of local redis.
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/1")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="")
CELERY_TIME_ZONE = TIME_ZONE

if find_spec("django_celery_beat") is not None:
    CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
    INSTALLED_APPS.append("django_celery_beat")

#######################################################################################
# SECTION: Django-RQ configuration
#######################################################################################
# Configure Redis Queue for background job processing
RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "default",
        "DEFAULT_TIMEOUT": 360,
    },
}
RQ_SHOW_ADMIN_LINK = True

#######################################################################################
# SECTION: LOGGING CONFIGURATION
#######################################################################################
# A logging configuration suitable for production.
LOG_DIR = env("LOG_DIR", default=DATA_DIR / "logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # Keeps Django's default loggers and handlers
    "formatters": {
        "detailed": {
            "format": "{asctime} [{levelname}] {name}.{module}:{lineno} - {message}",
            "style": r"{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "maxBytes": 1024 * 1024 * 1024,  # 1 GB
            "backupCount": 5,
            "formatter": "detailed",
        },
        # A separate log for errors, to be monitored more closely.
        "errorlog": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "error.log",
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 5,
            "formatter": "detailed",
        },
        # Django's console handler logs nothing if DEBUG is False, so we redeclare it.
        # This allows Docker/Kubernetes to capture logs from the console in prod.
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "detailed",
        },
    },
    "loggers": {
        # Django declares the "django" logger, but sends output only to console.
        "django": {
            "handlers": ["file", "console", "errorlog"],
            "level": "INFO",
            "propagate": False,  # Prevent duplicate logging
        },
        # "django.server" is effectively the access log. Django's default sends
        # it only to console.
        "django.server": {
            "handlers": ["file", "console", "errorlog"],
            "level": "INFO",
            "propagate": False,
        },
        # Log messages from your own project at INFO level.
        PROJECT: {
            "handlers": ["file", "console", "errorlog"],
            "level": "INFO",
            "propagate": False,
        },
        # Third party libraries can be noisy, so only capture warnings/errors.
        "": {
            "handlers": ["file", "console", "errorlog"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
# A separate config for local development, which includes rich logging.
DEBUG_LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # Keeps Django's default loggers and handlers
    "formatters": {
        "detailed": {
            "format": "{asctime} [{levelname}] {name}.{module}:{lineno} - {message}",
            "style": r"{",
        },
        "rich": {
            "datefmt": "[%X]",
        },
    },
    "handlers": {
        # In dev, log to a file for debugging, rotate daily for a fresh start.
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "when": "midnight",  # Rotate logs daily at midnight
            "interval": 1,  # Every 1 day
            "backupCount": 7,  # Keep last 7 days of logs
            "encoding": "utf-8",
            "formatter": "detailed",
        },
        # Beautiful and useful console output with rich
        # https://www.willmcgugan.com/blog/tech/post/richer-django-logging/
        "console": {
            "level": "DEBUG",
            "class": "rich.logging.RichHandler",
            "formatter": "rich",
        },
    },
    "loggers": {
        # Django declares the "django" logger, but sends output only to console.
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,  # Prevent duplicate logging
        },
        # "django.server" is effectively the access log. Django's default sends
        # it only to console.
        "django.server": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        # Log messages from your own project at DEBUG level.
        PROJECT: {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Third party libraries can be noisy, adjust accordingly.
        "": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
if DEBUG:
    LOGGING = DEBUG_LOGGING

#######################################################################################
# SECTION: DEVELOPMENT: If running in a dev environment, loosen restrictions
# and add debugging tools.
#######################################################################################
if DEBUG:
    ALLOWED_HOSTS = ["*"]

    if find_spec("debug_toolbar") is not None and "test" not in sys.argv:
        INSTALLED_APPS.append("debug_toolbar")
        MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
        INTERNAL_IPS = ["127.0.0.1"]
        # The documented way to do this in docker is to use
        # debug_toolbar.middleware.show_toolbar_with_docker, but that isn't working for
        # me. If DEBUG is True and we're not testing, just show the toolbar always.
        DEBUG_TOOLBAR_CONFIG = {
            "SHOW_TOOLBAR_CALLBACK": lambda request: True,
        }
        # See also urls.py for debug_toolbar urls
